Fix missing echo

diff --git a/extra/github-actions/build-linux-arm.yml b/extra/github-actions/build-linux-arm.yml
--- a/extra/github-actions/build-linux-arm.yml
+++ b/extra/github-actions/build-linux-arm.yml
@@ -104,6 +104,6 @@
   run: |
     [[ $NEEDCOMMIT ]] && git -C haxe_bin tag linux$BUILDARCH-$GITHUB_SHA || echo "No commit necessary"
 - name: Push binary
-  run: git -C haxe_bin push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/haxe_bin.git master --tags || "WARNING! Push binary failed. This is supposed to fail on forked repositories."
+  run: git -C haxe_bin push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/haxe_bin.git master --tags || echo "WARNING! Push binary failed. This is supposed to fail on forked repositories."
   env:
     ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}
